;
; File generated by cc65 v 2.15 - Git f7cdfbf
;
	.fopt		compiler,"cc65 v 2.15 - Git f7cdfbf"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_led_init
	.import		_led_set
	.import		_acia_init
	.import		_acia_puts
	.import		_acia_gets
	.export		_print_buffer
	.export		_ison
	.export		_main

.segment	"RODATA"

L000A:
	.byte	$36,$35,$30,$32,$20,$48,$6F,$6D,$65,$43,$6F,$6D,$70,$75,$74,$65
	.byte	$72,$20,$72,$65,$61,$64,$79,$2E,$0D,$0A,$00
L0011:
	.byte	$54,$79,$70,$65,$20,$73,$6F,$6D,$65,$74,$68,$69,$6E,$67,$2E,$0D
	.byte	$0A,$00
L0017:
	.byte	$59,$6F,$75,$20,$74,$79,$70,$65,$64,$3A,$20,$00
L001C	:=	L000A+24

.segment	"BSS"

_print_buffer:
	.res	80,$00
_ison:
	.res	2,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldy     #$00
	jsr     _led_init
	jsr     _acia_init
	lda     #$00
	sta     _ison
	sta     _ison+1
	sta     _print_buffer
	lda     #<(L000A)
	ldx     #>(L000A)
	jsr     _acia_puts
L000F:	lda     #<(L0011)
	ldx     #>(L0011)
	jsr     _acia_puts
	lda     #<(_print_buffer)
	ldx     #>(_print_buffer)
	jsr     pushax
	lda     #$FF
	jsr     _acia_gets
	lda     #<(L0017)
	ldx     #>(L0017)
	jsr     _acia_puts
	lda     #<(_print_buffer)
	ldx     #>(_print_buffer)
	jsr     _acia_puts
	lda     #<(L001C)
	ldx     #>(L001C)
	jsr     _acia_puts
	lda     _ison
	ora     _ison+1
	bne     L001E
	tax
	lda     #$01
	jmp     L002A
L001E:	ldx     #$00
	txa
L002A:	sta     _ison
	stx     _ison+1
	lda     _ison
	jsr     _led_set
	jmp     L000F

.endproc

